### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [buithuynhung/FlappyBird#1]
1. Реализация подсчёта очков (метод `getScore()`) предполагает, что пользователь класса обязан вызывать этот метод на каждом шаге игры, иначе очки могут посчитаться некорректно. Это неправильно: подсчёт очков должен быть привязан к шагу игры (метод `step`), а `getScore()` должен только возвращать текущее количество очков.
1. Мне не нравится, Ваш класс `Size`. Во-первых, зачем Вы что-то привязываете к размеру экрана, а не фрейма? Во-вторых, я бы всё-таки хотел, чтобы размеры поля передавались из `MainFrame` в конструкторы тех классов, где они нужны, например `Game`. В-третьих, возможно не стоит заводить целый класс для констант, возможно лучше их объявить в конкретных классах. Если же оставлять класс с константами, то они в любом случае должны быть статическими, чтобы не нужно было создавать экземпляр объекта для их использования.
1. Вы убрали не все "магические числа", например, в `Pipes`.
1. В нескольких местах дублируется код при обработке 3 труб. Попробуйте избавиться от дублирования кода.
1. Нет тестов

**Comment by buithuynhung** [comment]
Подскажите мне, пожалуйста, если я не смогу сдать игру до 29 мая, мне можно пойти на срочный экзамен или нет?

**Comment by maximpetrov** [comment]
Да, на экзамен 29 мая Вы можете придти независимо от того, сдадите Вы 3 задание или нет.

**Comment by buithuynhung** [comment]
да. Спасибо вам!)

**Comment by buithuynhung** [comment]
Проверите исправление, пожалуйста!

**Comment by maximpetrov** [comment]
Метод `addPipe` в `Game` должен быть приватным.
